### ISSUE TITLE
Homework 1 - Tadios

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479/tabletop-nerds#8]
As the project lead, I would like to see your bio included in our project documentation so we know who to credit for the work done on this application.

#### Acceptance Criteria
- clone this repository
- create your own branch off of master
- add a `bios/firstname-lastname.md` file to the project (e.g. `bios/andrew-harris.md`) with a paragraph of text containing the following information:
  1. Your CSCC major/track
  2. Why you are interested in web development
  3. What you want to be doing after you graduate
  4. What you do when you are not working
- commit your work
- push your branch to this repository
- create a pull request to merge your branch into master
- assign me as the code reviewer
- Move this issue to the "Done" column on the project board

**Comment by tdesta7** [comment]
working on HW#1
